### PR TITLE
Feat/mcp 93/multiple cloudrun revisions

### PR DESCRIPTION
**Pull request by AlexBMes**

### CODE REVIEW

**Comment by gbmeuk** [comment]
How are you expecting actor number 3 from performing automated deployments and changing traffic levels in this implementation?

**Comment by AlexBMes** [comment]
> How are you expecting actor number 3 from performing automated deployments and changing traffic levels in this implementation?

Sorry I did have a comment drafted in jira related to this but didn't send.

For this adapter since the management of traffic is within the `google_cloud_run_service resource`, I am not sure how to simplify the use for an automated user. 

If deploying multiple versions with traffic split users will always have to specify which revisions have traffic . Unless it is 100% to the latest revision, which isn’t relevant to multiple versions being managed. 100% of traffic to the latest revision is the default. 

I presume there would be some rollout policy where they would normally have a similar traffic split for each update. So I presumed that if a traffic split was:

```
traffic:
  - percent: 40          # Going to latest revision
  - revision_name: default-v1
    percent: 60
```

They would then update the traffic split to be:
```
traffic:
  - percent: 40 
  - revision_name: default-v2
    percent: 60
```
on the next update. And that would be an change of string from `v1` with `v2`, since all revisions start with the name of the service

**Comment by gbmeuk** [comment]
> > How are you expecting actor number 3 from performing automated deployments and changing traffic levels in this implementation?
> 
> Sorry I did have a comment drafted in jira related to this but didn't send.
> 
> For this adapter since the management of traffic is within the `google_cloud_run_service resource`, I am not sure how to simplify the use for an automated user.
> 
> If deploying multiple versions with traffic split users will always have to specify which revisions have traffic . Unless it is 100% to the latest revision, which isn’t relevant to multiple versions being managed. 100% of traffic to the latest revision is the default.
> 
> I presume there would be some rollout policy where they would normally have a similar traffic split for each update. So I presumed that if a traffic split was:
> 
> ```
> traffic:
>   - percent: 40          # Going to latest revision
>   - revision_name: default-v1
>     percent: 60
> ```
> 
> They would then update the traffic split to be:
> 
> ```
> traffic:
>   - percent: 40 
>   - revision_name: default-v2
>     percent: 60
> ```
> 
> on the next update. And that would be an change of string from `v1` with `v2`, since all revisions start with the name of the service

What if we make MCP traffic selection a totally different key space so that it could be easily assume what input variables would be required for a traffic selection map and more easily constructed? Separate file maybe.

**Comment by AlexBMes** [comment]
>What if we make MCP traffic selection a totally different key space so that it could be easily assume what input variables would be required for a traffic selection map and more easily constructed? Separate file maybe.
  
So is this suggesting having a `gcp_cloudrun_traffic.yml` file? Would a configuration like below work? 
```yaml
app1-v3: 40
app1-v2: 60
app2-v1.1: 20
app2-v1.0: 80
```
This could then use [`regexall`](https://www.terraform.io/docs/configuration/functions/regexall.html) to determine the service to be applying the traffic to. So have something like the following in locals:
```hcl
traffic = {
  for service, specs in local.cloudrun_specs: service => {
    for revision, percent in local.traffic_file: revision => percent
      if length(regexall("^${service}", revision)) > 0
  }
}
```

**Comment by gbmeuk** [comment]
> > What if we make MCP traffic selection a totally different key space so that it could be easily assume what input variables would be required for a traffic selection map and more easily constructed? Separate file maybe.
> 
> So is this suggesting having a `gcp_cloudrun_traffic.yml` file? Would a configuration like below work?
> 
> ```yaml
> app1-v3: 40
> app1-v2: 60
> app2-v1.1: 20
> app2-v1.0: 80
> ```
> 
> This could then use [`regexall`](https://www.terraform.io/docs/configuration/functions/regexall.html) to determine the service to be applying the traffic to. So have something like the following in locals:
> 
> ```terraform
> traffic = {
>   for service, specs in local.cloudrun_specs: service => {
>     for revision, percent in local.traffic_file: revision => percent
>       if length(regexall("^${service}", revision)) > 0
>   }
> }
> ```

Yes. Was thinking something like this. The other option we discussed was to have the adapters accept a variable for traffic, that defaults to 100% of the latest/default version. Then, if the DevOps actor wanted the automation actor to be able to declare a variable in the deployment module, where this variable can be defined through the use of an environment variable, and passed to the MCP module. Something like this:

```
terraform {
  backend "gcs" {
    bucket  = "app-bucket"
    prefix  = "tf_state"
  }
}

variable traffic_director {
  type = map(string)
  description = "Sets values of amount of traffic between application versions"
}

module "deployment" {
  source = "github.com/mesoform/terraform-infrastructure-modules/mcp"
  gae_traffic_director = var.traffic_director
}

output "module_gae_out" {
  value = module.deployment.gae
}

output "module_common_out" {
  value = module.deployment.project
}
```

**Comment by AlexBMes** [comment]
I think using the file `cloudrun_traffic.yml` is the best option. 

If using environment variables to declare a map the user would do :

```bash
$ TF_VAR_cloudrun_traffic='{"default-0" = 60, "default-1" = 40, "other-0" = 70, "other-1" = 30}'
or
$ TF_VAR_cloudrun_traffic='{"default" = { default-0 = 60, "default-1" = 40 }, "other" = {"other-0" = 70, "other-1" = 30}'
```

If it is the first environment variable format, the definition for `local.cloudrun_traffic` would be pretty much the same as the definition used if using a file.
```hcl
cloudrun_traffic = {
  for service, specs in local.cloudrun_specs: service => {
    for revision, percent in var.cloudrun_traffic: revision => percent
    if length(regexall("^${service}", revision)) > 0
  }
}
```

if it was using the second format it would be:

```hcl
cloudrun_traffic = {
	for service, revisions in var.cloudrun_traffic service => revisions
	if lookup(local.cloudrun_specs, service, null) != null
}
```

I think that the using environment variables wouldn't be as simple for a non-automated user as using `cloudrun_traffic.yml`. Using the file would be clear for both types of user. 

I think this format would also work for an app engine traffic split if it were to be within mcp. The user could import the traffic split for each service when using a new workspace. 

Having [`google_app_engine_service_split_traffic`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/app_engine_service_split_traffic) within mcp would mean that it can default to sending 100% of the traffic to the version just made. This would mean that replacing an old version with a new version will no longer error.

**Review by gbmeuk — APPROVED** [review]
Assuming that traffic details will be updated later

**Pull request merged**
